spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager?autoReconnect=true&useSSL=true
    username: root
    password: q11W22e33#
  jpa:
    hibernate:
      ddl-auto: update
      dialect:
        storage_engine: innodb
  kafka:
    bootstrap-servers: "localhost:9092"
    topic:
      rating: "RATING_EVENT_SOURCING"
      group: 1234
