spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manager?autoReconnect=true&useSSL=false&sessionVariables=storage_engine=InnoDB
    username: root
    password: q11W22e33#
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  kafka:
    bootstrap-servers: "localhost:9092"
    topic:
      rating: "RATING_EVENT_SOURCING"
      group: 1234
