spring:
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: "localhost:9092"
    topic:
      coordinate: "coordinate"
      group: 1234
jwt:
  secret: _@HRL&L3tF?Z7ccj4z&L5!nU2B!Rjs3_
  expiration: 604800