spring:
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: "localhost:9092"
    topic:
      coordinate: "COORDINATE_EVENT_SOURCING"
      group: 1234
nasa-api:
  api-key: DEMO_KEY
  api-version: 1.0
  api-feed-type: json
